// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/activity/record.proto

package activity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 获取记录列表的请求
type RecordFetchRequest struct {
	StartTime            int64    `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int64    `protobuf:"varint,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Notification         string   `protobuf:"bytes,3,opt,name=notification,proto3" json:"notification,omitempty"`
	Action               string   `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordFetchRequest) Reset()         { *m = RecordFetchRequest{} }
func (m *RecordFetchRequest) String() string { return proto.CompactTextString(m) }
func (*RecordFetchRequest) ProtoMessage()    {}
func (*RecordFetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ca17cf1a8e4e2c, []int{0}
}

func (m *RecordFetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordFetchRequest.Unmarshal(m, b)
}
func (m *RecordFetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordFetchRequest.Marshal(b, m, deterministic)
}
func (m *RecordFetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordFetchRequest.Merge(m, src)
}
func (m *RecordFetchRequest) XXX_Size() int {
	return xxx_messageInfo_RecordFetchRequest.Size(m)
}
func (m *RecordFetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordFetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecordFetchRequest proto.InternalMessageInfo

func (m *RecordFetchRequest) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *RecordFetchRequest) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RecordFetchRequest) GetNotification() string {
	if m != nil {
		return m.Notification
	}
	return ""
}

func (m *RecordFetchRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

// 获取记录列表的回复
type RecordFetchResponse struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Record               []*RecordEntity `protobuf:"bytes,2,rep,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RecordFetchResponse) Reset()         { *m = RecordFetchResponse{} }
func (m *RecordFetchResponse) String() string { return proto.CompactTextString(m) }
func (*RecordFetchResponse) ProtoMessage()    {}
func (*RecordFetchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ca17cf1a8e4e2c, []int{1}
}

func (m *RecordFetchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordFetchResponse.Unmarshal(m, b)
}
func (m *RecordFetchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordFetchResponse.Marshal(b, m, deterministic)
}
func (m *RecordFetchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordFetchResponse.Merge(m, src)
}
func (m *RecordFetchResponse) XXX_Size() int {
	return xxx_messageInfo_RecordFetchResponse.Size(m)
}
func (m *RecordFetchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordFetchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecordFetchResponse proto.InternalMessageInfo

func (m *RecordFetchResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RecordFetchResponse) GetRecord() []*RecordEntity {
	if m != nil {
		return m.Record
	}
	return nil
}

func init() {
	proto.RegisterType((*RecordFetchRequest)(nil), "activity.RecordFetchRequest")
	proto.RegisterType((*RecordFetchResponse)(nil), "activity.RecordFetchResponse")
}

func init() {
	proto.RegisterFile("proto/activity/record.proto", fileDescriptor_d3ca17cf1a8e4e2c)
}

var fileDescriptor_d3ca17cf1a8e4e2c = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x49, 0x03, 0x86, 0x4e, 0x59, 0xa0, 0x41, 0xaa, 0xac, 0x52, 0xa4, 0x28, 0xab, 0xac,
	0x52, 0x29, 0x9c, 0x81, 0xae, 0x91, 0xe1, 0x02, 0x26, 0x35, 0xaa, 0x17, 0x78, 0x8a, 0x3d, 0x45,
	0xea, 0x0d, 0x38, 0x36, 0x62, 0x92, 0xa8, 0x34, 0x52, 0x97, 0xf3, 0xfe, 0x1f, 0xfb, 0xcf, 0x87,
	0x87, 0x5d, 0x24, 0xa6, 0x95, 0x6d, 0xd9, 0x7f, 0x7b, 0x3e, 0xac, 0xa2, 0x6b, 0x29, 0x6e, 0x6a,
	0xa1, 0x78, 0x33, 0xe0, 0xc5, 0xd8, 0x96, 0xb6, 0x36, 0xba, 0xde, 0x56, 0xfe, 0x64, 0x80, 0x46,
	0xf6, 0xd6, 0x8e, 0xdb, 0xad, 0x71, 0x5f, 0x7b, 0x97, 0x18, 0x97, 0x30, 0x4d, 0x6c, 0x23, 0xbf,
	0xf9, 0x4f, 0xa7, 0xb3, 0x22, 0xab, 0x72, 0x73, 0x04, 0xa8, 0xe1, 0xda, 0x85, 0x8d, 0x68, 0x13,
	0xd1, 0x86, 0x11, 0x4b, 0xb8, 0x0d, 0xc4, 0xfe, 0xc3, 0xb7, 0x96, 0x3d, 0x05, 0x9d, 0x17, 0x59,
	0x35, 0x35, 0x27, 0x0c, 0xe7, 0xa0, 0xfe, 0xb2, 0x50, 0xd0, 0x97, 0xa2, 0xf6, 0x53, 0x49, 0x70,
	0x7f, 0x92, 0x24, 0xed, 0x28, 0x24, 0x87, 0x15, 0xa8, 0xc4, 0x96, 0xf7, 0x49, 0x72, 0xcc, 0x9a,
	0xbb, 0x7a, 0xb8, 0xa4, 0x7e, 0x15, 0x6e, 0x7a, 0x1d, 0x6b, 0x50, 0x5d, 0x05, 0x7a, 0x52, 0xe4,
	0xd5, 0xac, 0x99, 0x1f, 0x9d, 0xdd, 0xc3, 0xcf, 0x81, 0x3d, 0x1f, 0x4c, 0xef, 0x6a, 0x5e, 0x40,
	0x75, 0x1c, 0xd7, 0x70, 0x25, 0x9f, 0xe2, 0x72, 0xbc, 0xf2, 0xbf, 0x95, 0xc5, 0xe3, 0x19, 0xb5,
	0x4b, 0x5a, 0x5e, 0xbc, 0x2b, 0x29, 0xf5, 0xe9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x45, 0xd6, 0xf8,
	0x5a, 0x9a, 0x01, 0x00, 0x00,
}
