// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/activity/shared.proto

package activity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 状态
type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65c0a780a740dc5, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BlankResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlankResponse) Reset()         { *m = BlankResponse{} }
func (m *BlankResponse) String() string { return proto.CompactTextString(m) }
func (*BlankResponse) ProtoMessage()    {}
func (*BlankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65c0a780a740dc5, []int{1}
}

func (m *BlankResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlankResponse.Unmarshal(m, b)
}
func (m *BlankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlankResponse.Marshal(b, m, deterministic)
}
func (m *BlankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlankResponse.Merge(m, src)
}
func (m *BlankResponse) XXX_Size() int {
	return xxx_messageInfo_BlankResponse.Size(m)
}
func (m *BlankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlankResponse proto.InternalMessageInfo

func (m *BlankResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// 操作员
type Operator struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operator) Reset()         { *m = Operator{} }
func (m *Operator) String() string { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()    {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65c0a780a740dc5, []int{2}
}

func (m *Operator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operator.Unmarshal(m, b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
}
func (m *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(m, src)
}
func (m *Operator) XXX_Size() int {
	return xxx_messageInfo_Operator.Size(m)
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Operator) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// 频道实体
type ChannelEntity struct {
	Notification         string   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	Alias                string   `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelEntity) Reset()         { *m = ChannelEntity{} }
func (m *ChannelEntity) String() string { return proto.CompactTextString(m) }
func (*ChannelEntity) ProtoMessage()    {}
func (*ChannelEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65c0a780a740dc5, []int{3}
}

func (m *ChannelEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelEntity.Unmarshal(m, b)
}
func (m *ChannelEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelEntity.Marshal(b, m, deterministic)
}
func (m *ChannelEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelEntity.Merge(m, src)
}
func (m *ChannelEntity) XXX_Size() int {
	return xxx_messageInfo_ChannelEntity.Size(m)
}
func (m *ChannelEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelEntity.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelEntity proto.InternalMessageInfo

func (m *ChannelEntity) GetNotification() string {
	if m != nil {
		return m.Notification
	}
	return ""
}

func (m *ChannelEntity) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

// 记录实体
type RecordEntity struct {
	Operator             *Operator      `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Channel              *ChannelEntity `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Action               string         `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Head                 string         `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`
	Body                 string         `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Time                 int64          `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RecordEntity) Reset()         { *m = RecordEntity{} }
func (m *RecordEntity) String() string { return proto.CompactTextString(m) }
func (*RecordEntity) ProtoMessage()    {}
func (*RecordEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65c0a780a740dc5, []int{4}
}

func (m *RecordEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordEntity.Unmarshal(m, b)
}
func (m *RecordEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordEntity.Marshal(b, m, deterministic)
}
func (m *RecordEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordEntity.Merge(m, src)
}
func (m *RecordEntity) XXX_Size() int {
	return xxx_messageInfo_RecordEntity.Size(m)
}
func (m *RecordEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordEntity.DiscardUnknown(m)
}

var xxx_messageInfo_RecordEntity proto.InternalMessageInfo

func (m *RecordEntity) GetOperator() *Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (m *RecordEntity) GetChannel() *ChannelEntity {
	if m != nil {
		return m.Channel
	}
	return nil
}

func (m *RecordEntity) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *RecordEntity) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *RecordEntity) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *RecordEntity) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Status)(nil), "activity.Status")
	proto.RegisterType((*BlankResponse)(nil), "activity.BlankResponse")
	proto.RegisterType((*Operator)(nil), "activity.Operator")
	proto.RegisterType((*ChannelEntity)(nil), "activity.ChannelEntity")
	proto.RegisterType((*RecordEntity)(nil), "activity.RecordEntity")
}

func init() {
	proto.RegisterFile("proto/activity/shared.proto", fileDescriptor_f65c0a780a740dc5)
}

var fileDescriptor_f65c0a780a740dc5 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xc9, 0xd7, 0x36, 0x6d, 0x6f, 0x5b, 0xf8, 0x18, 0x44, 0x07, 0xdc, 0x94, 0xac, 0xb2,
	0x4a, 0xb1, 0x8a, 0xe0, 0x56, 0x71, 0xe1, 0x4a, 0x18, 0x9f, 0xe0, 0x36, 0xb9, 0x9a, 0xc1, 0x74,
	0x26, 0x64, 0x46, 0x21, 0x0f, 0xe8, 0x7b, 0xc9, 0xfc, 0xb3, 0x74, 0x77, 0xee, 0xc9, 0xc9, 0xb9,
	0xbf, 0x9b, 0xc0, 0x75, 0x3f, 0x68, 0xab, 0x77, 0x58, 0x5b, 0xf9, 0x2d, 0xed, 0xb8, 0x33, 0x2d,
	0x0e, 0xd4, 0x54, 0xde, 0x65, 0x8b, 0x64, 0x17, 0xf7, 0x90, 0xbf, 0x59, 0xb4, 0x5f, 0x86, 0x31,
	0x98, 0xd6, 0xba, 0x21, 0x9e, 0x6d, 0xb3, 0x72, 0x26, 0xbc, 0x66, 0x1c, 0xe6, 0x47, 0x32, 0x06,
	0x3f, 0x88, 0xff, 0xdb, 0x66, 0xe5, 0x52, 0xa4, 0xb1, 0x78, 0x80, 0xcd, 0x63, 0x87, 0xea, 0x53,
	0x90, 0xe9, 0xb5, 0x32, 0xc4, 0x4a, 0xc8, 0x8d, 0x2f, 0xf2, 0x05, 0xab, 0xfd, 0xff, 0x2a, 0xed,
	0xa8, 0xc2, 0x02, 0x11, 0x9f, 0x17, 0x77, 0xb0, 0x78, 0xed, 0x69, 0x40, 0xab, 0x07, 0x76, 0x01,
	0xb3, 0x0e, 0x0f, 0xd4, 0xf9, 0x97, 0x96, 0x22, 0x0c, 0x0e, 0xc5, 0x8e, 0x7d, 0xda, 0xe9, 0x75,
	0xf1, 0x02, 0x9b, 0xa7, 0x16, 0x95, 0xa2, 0xee, 0x59, 0x59, 0x69, 0x47, 0x56, 0xc0, 0x5a, 0x69,
	0x2b, 0xdf, 0x65, 0x8d, 0x56, 0x6a, 0x15, 0x1b, 0xce, 0x3c, 0x57, 0x8f, 0x9d, 0x44, 0x13, 0x9b,
	0xc2, 0x50, 0xfc, 0x64, 0xb0, 0x16, 0x54, 0xeb, 0xa1, 0x89, 0x55, 0x15, 0x2c, 0x74, 0x24, 0x8a,
	0xf4, 0xec, 0x44, 0x9f, 0x58, 0xc5, 0x5f, 0x86, 0xdd, 0xc0, 0xbc, 0x0e, 0x2c, 0xbe, 0x78, 0xb5,
	0xbf, 0x3a, 0xc5, 0xcf, 0x20, 0x45, 0xca, 0xb1, 0x4b, 0xc8, 0x5d, 0x44, 0x2b, 0x3e, 0xf1, 0x28,
	0x71, 0x72, 0xa7, 0xb6, 0x84, 0x0d, 0x9f, 0x86, 0x53, 0x9d, 0x76, 0xde, 0x41, 0x37, 0x23, 0x9f,
	0x05, 0xcf, 0x69, 0xff, 0x49, 0xe4, 0x91, 0x78, 0xbe, 0xcd, 0xca, 0x89, 0xf0, 0xfa, 0x90, 0xfb,
	0x9f, 0x79, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xb1, 0x0e, 0x5e, 0xeb, 0x01, 0x00, 0x00,
}
